#!/usr/bin/env bash

# Create Git worktrees for features — single or batch.
#
# Modes:
#   - Subcommand "single": Create one worktree for a branch (lightweight; no env bootstrap).
#   - Mode C: Auto-detected; phase-merged prompts under prompts/features_by_phase/phase-*.md
#   - Mode B: Auto-detected; plan-aware using prompts/plan/features_plan.json + prompts/features/
#   - Mode A: Auto-detected; file-driven using prompts/features/* when no plan/phase files present
#
# For batch modes, the script writes prompts/FEATURE_PROMPT.txt into each worktree.
# The "single" subcommand writes a per-worktree .env with log/trace paths.
#
set -euo pipefail

usage_single() {
  cat <<'USAGE' >&2
Usage: scripts/create_feature_worktrees.sh single --branch <name> [--base <ref>] [--path <dir>] [--remote <name>] [--push]

Create a lightweight git worktree for one branch and write a per-worktree .env
with INSPECT_LOG_DIR and INSPECT_TRACE_FILE. Designed for speed in batch flows.

Options:
  --branch <name>   Branch to create/use (e.g., feat/foo)
  --base <ref>      Base ref if creating new branch (default: origin/main)
  --path <dir>      Target directory (default: ../<repo>-<branch>)
  --remote <name>   Remote for optional push (default: origin)
  --push            Push branch and set upstream
USAGE
}

create_single_worktree() {
  local branch="$1" base_ref="$2" path="$3" remote_name="$4" do_push="$5"

  local repo_root repo_name safe_branch parent_dir branch_exists
  repo_root=$(git rev-parse --show-toplevel 2>/dev/null || true)
  [[ -z "$repo_root" ]] && { echo "Error: not inside a git repository." >&2; exit 2; }
  repo_name=$(basename "$repo_root")

  if [[ -z "$path" ]]; then
    safe_branch=${branch//\//-}
    parent_dir=$(cd "$repo_root/.." && pwd)
    path="$parent_dir/${repo_name}-${safe_branch}"
  fi

  # Prevent using a branch that's already checked out in another worktree
  if git worktree list --porcelain | grep -qE "^branch refs/heads/${branch}$"; then
    echo "Error: branch '$branch' is already checked out in another worktree." >&2
    exit 3
  fi

  if git show-ref --verify --quiet "refs/heads/$branch"; then
    branch_exists=yes
  else
    branch_exists=no
  fi

  mkdir -p "$(dirname "$path")"
  if [[ "$branch_exists" == "yes" ]]; then
    git worktree add "$path" "$branch"
  else
    git fetch --all --prune
    git worktree add -b "$branch" "$path" "$base_ref"
  fi

  echo "[ok] Worktree created at: $path (branch: $branch)"

  # Per-worktree .env for logs/traces
  safe_branch=${branch//\//-}
  local log_dir=".inspect/logs-$safe_branch" trace_file=".inspect/trace-$safe_branch.log"
  mkdir -p "$path/.inspect" "$path/$log_dir"
  {
    echo "# Auto-generated by create_feature_worktrees.sh single"
    echo "INSPECT_LOG_DIR=$log_dir"
    echo "INSPECT_TRACE_FILE=$trace_file"
  } > "$path/.env"
  echo "[ok] Wrote $path/.env with per-worktree log paths"

  if [[ "$do_push" == "yes" ]]; then
    echo "[ok] Pushing branch to $remote_name ..."
    (cd "$path" && git push -u "$remote_name" "$branch")
  fi

  echo "[done] Worktree '$branch' ready at: $path"
}

BASE_REF=${BASE_REF:-origin/inspect-ai-rewrite}
REMOTE=${REMOTE:-origin}
FEATURE_DIR=${FEATURE_DIR:-prompts/features}
PLAN_JSON=${PLAN_JSON:-prompts/plan/features_plan.json}
PHASE_DIR=${PHASE_DIR:-prompts/features_by_phase}

# Filters
PHASES=${PHASES:-}          # e.g., "1" or "1,2"; empty = all phases
GROUPS=${GROUPS:-}          # e.g., "A,B"; empty = all groups
DRY_RUN=${DRY_RUN:-0}       # 1 = print actions only
SKIP_EXISTING=${SKIP_EXISTING:-1}  # 1 = skip if branch/worktree already exists
MERGE_MODE=${MERGE_MODE:-block}    # block = one worktree per merged block; feature = one per feature inside block

REPO_NAME=$(basename "$(git rev-parse --show-toplevel)")

# --- Subcommand: single ---
if [[ "${1:-}" == "single" ]]; then
  shift || true
  BRANCH=""; BASE="$BASE_REF"; DEST_PATH=""; REMOTE="origin"; DO_PUSH="no"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --branch) BRANCH="${2:?}"; shift 2;;
      --base) BASE="${2:?}"; shift 2;;
      --path) DEST_PATH="${2:?}"; shift 2;;
      --remote) REMOTE="${2:?}"; shift 2;;
      --push) DO_PUSH="yes"; shift;;
      -h|--help) usage_single; exit 0;;
      *) echo "Unknown option for 'single': $1" >&2; usage_single; exit 2;;
    esac
  done
  [[ -z "$BRANCH" ]] && { echo "Error: --branch is required." >&2; usage_single; exit 2; }
  create_single_worktree "$BRANCH" "$BASE" "$DEST_PATH" "$REMOTE" "$DO_PUSH"
  exit 0
fi

mode_c() {
  echo "[02c] Using consolidated phase files in: $PHASE_DIR"
  SELECTED=$(PHASES="$PHASES" GROUPS="$GROUPS" PHASE_DIR="$PHASE_DIR" python - <<'PY'
import os, re, sys, glob, base64, unicodedata

phases_filter = {p.strip() for p in os.environ.get('PHASES','').split(',') if p.strip()}
groups_filter = {g.strip() for g in os.environ.get('GROUPS','').split(',') if g.strip()}
phase_dir = os.environ.get('PHASE_DIR','prompts/features_by_phase')

def slugify(s):
    s = unicodedata.normalize('NFKD', s).encode('ascii','ignore').decode()
    s = re.sub(r'\s+', '-', s.strip().lower())
    s = re.sub(r'[^a-z0-9-]', '', s)
    return s or 'block'

files = sorted(glob.glob(os.path.join(phase_dir, 'phase-*.md')))
for path in files:
    text = open(path, 'r', encoding='utf-8').read()
    mfile = re.search(r'phase-(\d+)', os.path.basename(path))
    phase = mfile.group(1) if mfile else ''
    if not phase:
        mh = re.search(r'^#\s*Phase\s*(\d+)', text, re.M)
        phase = mh.group(1) if mh else ''
    if not phase:
        continue
    if phases_filter and phase not in phases_filter:
        continue
    blocks = list(re.finditer(r'(?m)^##\s*Group\s+([A-Z])\s*:\s*(.+?)\s*$', text))
    for i, bh in enumerate(blocks, 1):
        group = bh.group(1)
        if groups_filter and group not in groups_filter:
            continue
        start = bh.start()
        end = blocks[i].start() if i < len(blocks) else len(text)
        block_text = text[start:end].strip() + "\n"
        block_name = bh.group(2)
        features = re.findall(r'\b(feat-[a-z0-9-]+)\b', block_text)
        seen = set(); order = []
        for f in features:
            if f not in seen:
                seen.add(f); order.append(f)
        feat_csv = ','.join(order)
        bslug = slugify(block_name) if block_name else (order[0] if order else f'block-{i:02d}')
        b64 = base64.b64encode(block_text.encode('utf-8')).decode('ascii')
        print('\t'.join([phase, group, bslug, block_name, str(i), feat_csv, path, b64]))
PY
  )

  if [[ -z "$SELECTED" ]]; then
    echo "[02c] No blocks matched filters (PHASES='$PHASES' GROUPS='$GROUPS').";
    return 0
  fi

  while IFS=$'\t' read -r PHASE GROUP BLOCK_SLUG BLOCK_NAME IDX FEAT_CSV SRC_FILE BLOCK_B64; do
    [[ -z "$PHASE" ]] && continue
    if [[ "$MERGE_MODE" == "block" ]]; then
      BRANCH="feat/p${PHASE}-g${GROUP}-${BLOCK_SLUG}"
      WORKTREE_PATH=".worktrees/${BLOCK_SLUG}"
      echo "==> Creating worktree for Block '$BLOCK_NAME' (phase $PHASE group $GROUP) → $BRANCH at $WORKTREE_PATH"
      if [[ "$DRY_RUN" != "1" ]]; then
        if [[ "$SKIP_EXISTING" == "1" ]] && (git show-ref --verify --quiet "refs/heads/$BRANCH" || git worktree list --porcelain | grep -qE "^branch refs/heads/$BRANCH$"); then
          echo "   Skipping existing $BRANCH"; continue; fi
        bash scripts/create_feature_worktrees.sh single --branch "$BRANCH" --base "$BASE_REF" --path "$WORKTREE_PATH"
        mkdir -p "$WORKTREE_PATH/prompts"
        {
          echo "# Source: $SRC_FILE (phase block)"; echo "# Branch: $BRANCH"; echo "# Phase: $PHASE"; echo "# Group: $GROUP"; echo "# Block: $BLOCK_NAME"; echo "# Features: $FEAT_CSV"; echo
          echo "$BLOCK_B64" | base64 -d
        } > "$WORKTREE_PATH/prompts/FEATURE_PROMPT.txt"
        echo "   Wrote $WORKTREE_PATH/prompts/FEATURE_PROMPT.txt"
      fi
    else
      IFS=',' read -r -a FEATS <<< "$FEAT_CSV"
      for FID in "${FEATS[@]}"; do
        FSLUG=${FID#feat-}
        BRANCH="feat/p${PHASE}-g${GROUP}-${FSLUG}"
        WORKTREE_PATH=".worktrees/${FSLUG}"
        echo "==> Creating worktree for Feature $FID (phase $PHASE group $GROUP) → $BRANCH at $WORKTREE_PATH"
        if [[ "$DRY_RUN" != "1" ]]; then
          if [[ "$SKIP_EXISTING" == "1" ]] && (git show-ref --verify --quiet "refs/heads/$BRANCH" || git worktree list --porcelain | grep -qE "^branch refs/heads/$BRANCH$"); then
            echo "   Skipping existing $BRANCH"; continue; fi
            bash scripts/create_feature_worktrees.sh single --branch "$BRANCH" --base "$BASE_REF" --path "$WORKTREE_PATH"
          mkdir -p "$WORKTREE_PATH/prompts"
          {
            echo "# Source: $SRC_FILE (phase block)"; echo "# Branch: $BRANCH"; echo "# Phase: $PHASE"; echo "# Group: $GROUP"; echo "# Focus Feature: $FID"; echo "# Block: $BLOCK_NAME"; echo "# All Features: $FEAT_CSV"; echo
            echo "$BLOCK_B64" | base64 -d
          } > "$WORKTREE_PATH/prompts/FEATURE_PROMPT.txt"
          echo "   Wrote $WORKTREE_PATH/prompts/FEATURE_PROMPT.txt"
        fi
      done
    fi
  done <<< "$SELECTED"
}

mode_b() {
  echo "[plan] Using plan file: $PLAN_JSON"
  SELECTED=$(PHASES="$PHASES" GROUPS="$GROUPS" FEATURE_DIR="$FEATURE_DIR" PLAN_JSON="$PLAN_JSON" python - <<'PY'
import json, os, re, unicodedata, glob
plan = os.environ.get('PLAN_JSON','prompts/plan/features_plan.json')
phases = {p.strip() for p in os.environ.get('PHASES','').split(',') if p.strip()}
groups = {g.strip() for g in os.environ.get('GROUPS','').split(',') if g.strip()}
feat_dir = os.environ.get('FEATURE_DIR','prompts/features')
with open(plan) as f:
    data = json.load(f)
features = data.get('features', [])

def slugify(s):
    s = unicodedata.normalize('NFKD', s).encode('ascii','ignore').decode()
    s = re.sub(r'\s+', '-', s.strip().lower())
    s = re.sub(r'[^a-z0-9-]', '', s)
    return s or 'feature'

def feat_slug(feat):
    fid = feat.get('id','')
    if fid.startswith('feat-'):
        return fid[len('feat-'):]
    return slugify(feat.get('name','feature'))

def find_prompt(slug, name):
    pats = [f"{feat_dir}/**/*{slug}*.md", f"{feat_dir}/**/*{slug}*.txt"]
    for p in pats:
        matches = sorted(glob.glob(p, recursive=True))
        if matches:
            return matches[0]
    tokens = [t for t in re.split(r'[^a-z0-9]+', name.lower()) if t]
    for ext in ('md','txt'):
        for path in sorted(glob.glob(f"{feat_dir}/**/*.{ext}", recursive=True)):
            base = os.path.basename(path).lower()
            if any(t in base for t in tokens[:3]):
                return path
    return ''

out = []
for feat in features:
    phase = str(feat.get('phase', 1))
    group = str(feat.get('parallel_group', 'A'))
    if phases and phase not in phases:
        continue
    if groups and group not in groups:
        continue
    slug = feat_slug(feat)
    name = feat.get('name', slug)
    prompt = find_prompt(slug, name)
    out.append((slug, phase, group, prompt, name))

for row in out:
    print('\t'.join(row))
PY
  )
  if [[ -z "$SELECTED" ]]; then
    echo "[plan] No features matched filters (PHASES='$PHASES' GROUPS='$GROUPS')."
  fi
  while IFS=$'\t' read -r SLUG PHASE GROUP PROMPT NAME; do
    [[ -z "$SLUG" ]] && continue
    BRANCH="feat/$SLUG"
    WORKTREE_PATH=".worktrees/${SLUG}"

    if [[ "$SKIP_EXISTING" == "1" ]]; then
      if git show-ref --verify --quiet "refs/heads/$BRANCH" || \
         git worktree list --porcelain | grep -qE "^branch refs/heads/$BRANCH$"; then
        echo "==> Skipping existing $BRANCH"
        continue
      fi
    fi

    echo "==> Creating worktree for $NAME (phase $PHASE group $GROUP) → $BRANCH at $WORKTREE_PATH"
    if [[ "$DRY_RUN" == "1" ]]; then
      continue
    fi

    bash scripts/create_feature_worktrees.sh single --branch "$BRANCH" --base "$BASE_REF" \
      --path "$WORKTREE_PATH"

    mkdir -p "$WORKTREE_PATH/prompts"
    if [[ -f "$PROMPT" ]]; then
      {
        echo "# Source: $PROMPT"; echo "# Branch: $BRANCH"; echo "# Phase: $PHASE"; echo "# Group: $GROUP"; echo "# Imported: $(date -u +%Y-%m-%dT%H:%M:%SZ)"; echo; cat "$PROMPT"
      } > "$WORKTREE_PATH/prompts/FEATURE_PROMPT.txt"
    else
      {
        echo "# Source: plan-only (no matching prompt file found in $FEATURE_DIR)"; echo "# Branch: $BRANCH"; echo "# Phase: $PHASE"; echo "# Group: $GROUP"; echo; echo "TODO: add the feature's prompt content here for traceability."
      } > "$WORKTREE_PATH/prompts/FEATURE_PROMPT.txt"
    fi
    echo "   Wrote $WORKTREE_PATH/prompts/FEATURE_PROMPT.txt"
  done <<< "$SELECTED"
}

mode_a() {
  echo "[plan] No plan JSON or phase files found — file-driven mode (Mode A)"
  find "$FEATURE_DIR" -type f \( -name '*.md' -o -name '*.txt' \) -print0 |
  while IFS= read -r -d '' FEAT_FILE; do
    NAME=$(basename "$FEAT_FILE")
    SLUG=$(echo "$NAME" | sed -E 's/\.[^.]+$//' | tr 'A-Z' 'a-z' | sed -E 's/[ _]+/-/g; s/[^a-z0-9-]+//g')
    BRANCH="feat/$SLUG"
    WORKTREE_PATH="../${REPO_NAME}-${SLUG}"

    echo "==> Creating worktree for $NAME → $BRANCH at $WORKTREE_PATH"
    if [[ "$DRY_RUN" != "1" ]]; then
      bash scripts/create_feature_worktrees.sh single --branch "$BRANCH" --base "$BASE_REF" \
        --path "$WORKTREE_PATH" --push
      mkdir -p "$WORKTREE_PATH/prompts"
      { echo "# Source: $FEAT_FILE"; echo "# Branch: $BRANCH"; echo "# Imported: $(date -u +%Y-%m-%dT%H:%M:%SZ)"; echo; cat "$FEAT_FILE"; } > "$WORKTREE_PATH/prompts/FEATURE_PROMPT.txt"
      echo "   Wrote $WORKTREE_PATH/prompts/FEATURE_PROMPT.txt"
    fi
  done
}

# --- Dispatch ---
if compgen -G "$PHASE_DIR/phase-*.md" > /dev/null; then
  mode_c
elif [[ -f "$PLAN_JSON" ]]; then
  mode_b
else
  mode_a
fi

echo "[done] Worktree creation process finished."
