#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'USAGE' >&2
Usage: scripts/new_worktree.sh <branch> [options]

Create a git worktree for parallel feature development and bootstrap a local
environment (uv or venv) plus a per-worktree .env with unique log/trace paths.

Arguments:
  <branch>                 New or existing branch name (e.g., feat/fs-atomic)

Options:
  --base <ref>             Base ref to branch from (default: origin/main)
  --path <dir>             Target directory for worktree (default: ../<repo>-<branch>)
  --remote <name>          Git remote to track/push (default: origin)
  --uv | --no-uv           Use uv sync if available (default: auto-detect)
  --venv | --no-venv       Create Python venv if uv is disabled/unavailable (default: on)
  --python <bin>           Python executable for venv (default: python3)
  --set-logs | --no-logs   Write .env with INSPECT_LOG_DIR/INSPECT_TRACE_FILE (default: on)
  --push                   Push new branch and set upstream (optional)
  -h, --help               Show this help

Examples:
  scripts/new_worktree.sh feat/fs-atomic
  scripts/new_worktree.sh chore/docs --base origin/main --no-uv --venv
  scripts/new_worktree.sh feat/profiles --path ../inspect_agents-profiles --push
USAGE
}

die() { echo "Error: $*" >&2; exit 1; }

# --- Defaults ---
BASE_REF="origin/main"
WORKTREE_PATH=""
REMOTE_NAME="origin"
USE_UV="auto"   # auto | yes | no
MAKE_VENV="yes" # yes | no (used when USE_UV=no or uv not present)
PY_BIN="python3"
WRITE_LOG_ENV="yes"
DO_PUSH="no"

# --- Parse args ---
[[ ${1:-} =~ ^(-h|--help)$ ]] && usage && exit 0
[[ $# -lt 1 ]] && usage && exit 2

BRANCH="$1"; shift || true

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base) BASE_REF="${2:?}"; shift 2;;
    --path) WORKTREE_PATH="${2:?}"; shift 2;;
    --remote) REMOTE_NAME="${2:?}"; shift 2;;
    --uv) USE_UV="yes"; shift;;
    --no-uv) USE_UV="no"; shift;;
    --venv) MAKE_VENV="yes"; shift;;
    --no-venv) MAKE_VENV="no"; shift;;
    --python) PY_BIN="${2:?}"; shift 2;;
    --set-logs) WRITE_LOG_ENV="yes"; shift;;
    --no-logs) WRITE_LOG_ENV="no"; shift;;
    --push) DO_PUSH="yes"; shift;;
    -h|--help) usage; exit 0;;
    *) die "Unknown option: $1";;
  esac
done

# --- Resolve repo root/name ---
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || true)
[[ -z "$REPO_ROOT" ]] && die "Not inside a git repository."
REPO_NAME=$(basename "$REPO_ROOT")

# --- Default worktree path ---
if [[ -z "$WORKTREE_PATH" ]]; then
  # sanitize branch for filesystem naming
  SAFE_BRANCH=${BRANCH//\//-}
  PARENT_DIR=$(cd "$REPO_ROOT/.." && pwd)
  WORKTREE_PATH="$PARENT_DIR/${REPO_NAME}-${SAFE_BRANCH}"
fi

# --- Ensure branch/worktree constraints ---
if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  BRANCH_EXISTS=yes
else
  BRANCH_EXISTS=no
fi

# Disallow reusing the same branch in another existing worktree.
if git worktree list --porcelain | grep -q "^branch $BRANCH$"; then
  die "Branch '$BRANCH' is already checked out in another worktree. Choose a new branch."
fi

# --- Create worktree ---
mkdir -p "$(dirname "$WORKTREE_PATH")"
if [[ "$BRANCH_EXISTS" == "yes" ]]; then
  git worktree add "$WORKTREE_PATH" "$BRANCH"
else
  git fetch --all --prune
  git worktree add -b "$BRANCH" "$WORKTREE_PATH" "$BASE_REF"
fi

echo "[ok] Worktree created at: $WORKTREE_PATH (branch: $BRANCH)"

# --- Create per-worktree .env and logs ---
if [[ "$WRITE_LOG_ENV" == "yes" ]]; then
  SAFE_BRANCH=${BRANCH//\//-}
  LOG_DIR=".inspect/logs-$SAFE_BRANCH"
  TRACE_FILE=".inspect/trace-$SAFE_BRANCH.log"
  mkdir -p "$WORKTREE_PATH/.inspect" "$WORKTREE_PATH/$LOG_DIR"
  {
    echo "# Auto-generated by scripts/new_worktree.sh"
    echo "INSPECT_LOG_DIR=$LOG_DIR"
    echo "INSPECT_TRACE_FILE=$TRACE_FILE"
  } > "$WORKTREE_PATH/.env"
  echo "[ok] Wrote $WORKTREE_PATH/.env with per-worktree log paths"
fi

# --- Bootstrap environment ---
cd "$WORKTREE_PATH"

have_uv() { command -v uv >/dev/null 2>&1; }

if [[ "$USE_UV" == "yes" || ( "$USE_UV" == "auto" && have_uv ) ]]; then
  if have_uv; then
    echo "[ok] Detected uv; syncing project deps..."
    uv sync || die "uv sync failed"
  else
    echo "[warn] uv requested but not found; falling back to venv"
    USE_UV="no"
  fi
fi

if [[ "$USE_UV" != "yes" && "$MAKE_VENV" == "yes" ]]; then
  echo "[ok] Creating Python venv with $PY_BIN ..."
  $PY_BIN -m venv .venv || die "venv creation failed"
  echo "[hint] Activate: source .venv/bin/activate; then pip install -e .[dev,testing]"
fi

# --- Optional: push new branch ---
if [[ "$DO_PUSH" == "yes" ]]; then
  echo "[ok] Pushing branch to $REMOTE_NAME ..."
  git push -u "$REMOTE_NAME" "$BRANCH"
fi

cat <<EOF

Next steps for $BRANCH:
- cd "$WORKTREE_PATH"
- (optional) export INSPECT_ENV_FILE=.env    # if your runner requires explicit pointing
- Run tests for the focused area, e.g.:
    CI=1 NO_NETWORK=1 PYTHONPATH=src:external/inspect_ai \
    uv run pytest -q tests/inspect_agents -k fs
- Commit only intended paths (avoid 'git add .'), then push:
    git add -p -- src/ docs/
    git commit -m "feat(<scope>): <summary>" -- src/ docs/
    git push -u $REMOTE_NAME $BRANCH

List worktrees:   git worktree list
Remove worktree:  git worktree remove "$WORKTREE_PATH" && git worktree prune

EOF

echo "[done] Worktree '$BRANCH' ready at: $WORKTREE_PATH"
